### ISSUE TITLE
Link columns with an array, don't change the layout when array is changing

### ISSUE THREAD

**Issue by ice-blaze** [angular-ui/ui-layout#142]
Hi there, here is the plunker, you just have to move the columns. 

http://embed.plnkr.co/gGksvQArxDranF2y6HYi/preview

You can see the array doing the swap but not the layout. Any idea on how to make the layout updating ?

Thanks.

**Comment by ice-blaze** [comment]
Must we use the `containers` array and simulate the same swap as the one done with the model ? https://github.com/angular-ui/ui-layout/blob/master/src/ui-layout.js#L18

Or have we to do in another way ?

**Comment by pheonixblade9** [comment]
This isn't a bug - you need to use track by in your ng-repeat in order to keep the index correct.

What you had before:

<div ui-layout-container ng-repeat="item in items" class="custom-back">

What you need:

<div ui-layout-container ng-repeat="item in items track by $index" class="custom-back">

http://plnkr.co/edit/KNLB4wD9SJLCYX6tp6aa?p=preview

**Comment by ice-blaze** [comment]
Ho thanks a lot !

**Comment by pheonixblade9** [comment]
Of course :)
