### ISSUE TITLE
Emit an event on resize

### ISSUE THREAD

**Issue by darabos** [angular-ui/ui-layout#34]
If you did a `scope.$emit('resized')` in `_resize()`, it would make it easy to implement arbitrary reactions to the new size.

**Comment by OverZealous** [comment]
:+1:

I think this is really, really important.  I have some CodeMirror instances inside ui-layout, and they absolutely need to be refreshed when a resize occurs.  I'm really stumped as to how to handle them right now, without seriously customizing ui-layout.

**Comment by mindjuice** [comment]
I added the following to the end of draw():

    //TODO: dispatch container resize event
    var containerIds = [];
    containerIds.push( beforeContainer.element.context.id );
    containerIds.push( afterContainer.element.context.id );
    $scope.$broadcast("resize", containerIds);

Then in my app, I added the following:

    return angular.element( $window ).bind( 'resize', function() {
       $scope.someFunctionOfYoursToRespondToResizeEvent();
       return $scope.$apply();
    } );

Not the best solution, but it is enough for my case.  I ended up not using the containerIds, but they might be useful for you depending on what you are doing.

**Comment by OverZealous** [comment]
For others who need this now, and don't want to modify the existing `ui-layout` module, I have a decent-enough hack that enables a global event simply by including this module in your applications:

```js
angular.module('oz.components.ui-layout-events', [
	'ui.layout'
])

	.directive('uiLayout', function($timeout, $rootScope) {
		var methods = ['updateDisplay', 'toggleBefore', 'toggleAfter', 'mouseUpHandler', 'mouseMoveHandler'],
			timer;

		function fireEvent() {
			if(timer) $timeout.cancel(timer);
			timer = $timeout(function() {
				$rootScope.$broadcast('ui.layout.resize');
				timer = null;
			}, 50);
		}

		return {
			restrict: 'AE',
			require: '^uiLayout',
			link: function(scope, elem, attrs, uiLayoutCtrl) {
				angular.forEach(methods, function(method) {
					var oldFn = uiLayoutCtrl[method];
					uiLayoutCtrl[method] = function() {
						oldFn.apply(uiLayoutCtrl, arguments);
						fireEvent();
					};
				});
			}
		};
	});
```

What this does is `$broadcast` an event on `$rootScope` any time UI-Layout updates, toggles a section, or resizes a splitter.  It uses `$timeout` to debounce the messages so it only fires once every 50ms or longer if you are dragging (so you don't get slow dragging due to a bunch of restyling events).

It works by overlapping the `uiLayout` directive (a totally awesome feature of Angular), and wrapping the existing methods for the `uiLayout` controller.

**Comment by mawic** [comment]
Are you still working on this? It would be great.
I tried OverZealous's workaround. But it continuously fires an event, if a container is resized. However, I only need an event at the end, like $element.trigger("resizeStop"); 

Do you have an idea how to solve it? Thanks!

**Comment by darabos** [comment]
It works great in 1.1.1, thanks a million! :+1:

**Comment by SomeKittens** [comment]
@darabos glad you liked it!
