### ISSUE TITLE
Programaticaly change sizes and refresh with nested

### ISSUE THREAD

**Issue by miriam-yodlr** [angular-ui/ui-layout#96]
Using the idea and plunker from https://github.com/angular-ui/ui-layout/issues/53 I tried to use it with nested containers.

http://plnkr.co/edit/isoiUTQ7pJ682inWy4eW?p=preview

The green area doesn't resize although the "size" variable updates. I am also having a problem where the green area doesn' t initialize with a variable at all, but does with a hard-coded size. (The problem is not in the plunker.)

Any help would be very much appreciated!

**Comment by dedelp** [comment]
Here is a working version. It appears each ui-layout needs to have it's own scope/controller. I've used a factory to control the sizes in this example so that any controller within the app can access/change them. I've read that rootScope broadcasts should be avoided, but couldn't come up with a better way in this instance. Hopefully someone else will have a better alternative.

http://plnkr.co/edit/wrszxvMUxpy2iOuz5XON?p=preview

Disclaimer: I am a relative noob with angular so I give no guarantees with the above code.

**Comment by miriam-yodlr** [comment]
Thank you dedelp that is very helpful!  (I'm an angular noob too.) Thank you!

**Comment by BobbieBarker** [comment]
Thank you for your contribution depelp.
